test: add GPU-accelerated decoding paths to CI tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -448,8 +448,18 @@ nvcf-helm:
       - awk -v ak="$AWS_ACCESS_KEY_ID" -v sk="$AWS_SECRET_ACCESS_KEY" -v rg="$AWS_DEFAULT_REGION"  '/aws_access_key_id/ {$0 = "aws_access_key_id = " ak} /aws_secret_access_key/ {$0 = "aws_secret_access_key = " sk} /region/ {$0 = "region = " rg} {print}' examples/nvcf/creds/aws_credentials > aws_credentials
       - sed -i '/^endpoint/d' aws_credentials
       # Split-annotate pipeline
-      - cat examples/nvcf/function/invoke_video_split_full.json | jq --arg output_clip_path "$S3_OUTPUT_CLIP_PATH" --arg input_video_path "$S3_INPUT_VIDEO_PATH" '.args.output_clip_path = $output_clip_path | .args.input_video_path = $input_video_path' > invoke_split.json
-      - cosmos-curate nvcf function invoke-function --data-file invoke_split.json --s3-config-file aws_credentials
+      # default config to process 1 video
+      - |
+        cat examples/nvcf/function/invoke_video_split_full.json | \
+        jq --arg output_clip_path "$S3_OUTPUT_CLIP_PATH" --arg input_video_path "$S3_INPUT_VIDEO_PATH" --argjson limit 1 \
+        '.args.output_clip_path = $output_clip_path | .args.input_video_path = $input_video_path | .args.limit = $limit' > invoke_split1.json
+      - cosmos-curate nvcf function invoke-function --data-file invoke_split1.json --s3-config-file aws_credentials
+      # use GPU decoding to process 1 more video
+      - |
+        cat examples/nvcf/function/invoke_video_split_full.json | \
+        jq --arg output_clip_path "$S3_OUTPUT_CLIP_PATH" --arg input_video_path "$S3_INPUT_VIDEO_PATH" --argjson limit 1 --arg transnetv2_frame_decoder_mode pynvc --argjson transnetv2_frame_decode_raise_on_pynvc_error true --argjson transcode_use_hwaccel true \
+        '.args.output_clip_path = $output_clip_path | .args.input_video_path = $input_video_path | .args.limit = $limit | .args.transnetv2_frame_decoder_mode = $transnetv2_frame_decoder_mode | .args.transnetv2_frame_decode_raise_on_pynvc_error = $transnetv2_frame_decode_raise_on_pynvc_error | .args.transcode_use_hwaccel = $transcode_use_hwaccel ' > invoke_split2.json
+      - cosmos-curate nvcf function invoke-function --data-file invoke_split2.json --s3-config-file aws_credentials
       # Dedup pipeline
       - cat examples/nvcf/function/invoke_video_dedup.json | jq --arg output_path "$S3_OUTPUT_DEDUP_PATH" --arg input_embeddings_path "$S3_OUTPUT_CLIP_PATH/iv2_embd_parquet/" '.args.output_path = $output_path | .args.input_embeddings_path = $input_embeddings_path' > invoke_dedup.json
       - cosmos-curate nvcf function invoke-function --data-file invoke_dedup.json --s3-config-file aws_credentials
@@ -473,7 +483,8 @@ nvcf-helm:
   artifacts:
     when: always
     paths:
-      - "invoke_split.json"
+      - "invoke_split1.json"
+      - "invoke_split2.json"
       - "invoke_dedup.json"
       - "invoke_shard.json"
       - "trace.log"
@@ -529,7 +540,6 @@ nvcf-helm-validate:
       fi
     - |
       echo "Validating $S3_FILE_SPLIT_SUMMARY ..."
-      SUMMARY_KEYWORDS=("num_input_videos" "num_processed_videos")
       JSON_CONTENT=$(aws s3 cp "$S3_FILE_SPLIT_SUMMARY" - 2>/dev/null)
       if [ $? -ne 0 ]; then
           echo "Error reading from S3: $S3_FILE_SPLIT_SUMMARY"
@@ -539,13 +549,22 @@ nvcf-helm-validate:
           echo "Error: Invalid JSON structure"
           exit 1
       fi
-      for key in "${SUMMARY_KEYWORDS[@]}"; do
-          val=$(jq -r ".$key" <<< "$JSON_CONTENT")
-          if ! [[ "$val" =~ ^[0-9]+$ ]] || [ "$val" -lt 0 ]; then
-              echo "Error: Unexpected $key : $val"
-              exit 1
-          fi
-      done
+      num_videos=$(jq -r ".num_processed_videos" <<< "$JSON_CONTENT")
+      if [ "$num_videos" -ne 2 ]; then
+          echo "Error: There should be 2 videos processed, but found $num_videos"
+          exit 1
+      fi
+      num_clips=$(jq -r ".num_clips_transcoded" <<< "$JSON_CONTENT")
+      num_clips_with_caption=$(jq -r ".num_clips_with_caption" <<< "$JSON_CONTENT")
+      if [ "$num_clips" -lt 2 ]; then
+          echo "Error: There should be at least 2 clips transcoded, but found $num_clips"
+          exit 1
+      fi
+      if [ "$num_clips_with_caption" -ne "$num_clips" ]; then
+          echo "Error: All clips should have captions, but found $num_clips_with_caption out of $num_clips"
+          exit 1
+      fi
+      echo "Split-annotate pipeline finished with $num_videos processed and $num_clips_with_caption captioned"
       echo "Split-annotate pipeline validation successful"
     - |
       set +e  # Disable exit on error
